-- Write your migrate up statements here
CREATE TABLE IF NOT EXISTS "user" (
    user_id         integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            text        NOT NULL,
    user_tag        text        NOT NULL UNIQUE,
    birth_date      date        NOT NULL,
    description     text,
    avatar_url      text        UNIQUE,
    deleted         boolean     NOT NULL DEFAULT false,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    deleted_at      timestamptz
);

COMMENT ON TABLE  "user"             IS 'Учётные записи пользователей';
COMMENT ON COLUMN "user".user_tag    IS 'Уникальный тег для поиска';
COMMENT ON COLUMN "user".avatar_url  IS 'Ссылка на аватар в MinIO';
COMMENT ON COLUMN "user".deleted     IS 'Так реализован soft delete: если delete = true — учётная запись удалёна';
COMMENT ON COLUMN "user".deleted_at  IS 'Момент soft delete; Если NULL, то запись активна';

CREATE OR REPLACE TRIGGER trg_user_check_age
BEFORE INSERT OR UPDATE OF birth_date ON "user"
FOR EACH ROW
EXECUTE FUNCTION check_user_age();

CREATE OR REPLACE TRIGGER trg_user_updated_at
BEFORE UPDATE ON "user"
FOR EACH ROW
WHEN (OLD.* IS DISTINCT FROM NEW.*)
EXECUTE FUNCTION fn_set_updated_at();

CREATE OR REPLACE TRIGGER trg_user_soft_delete
BEFORE UPDATE ON "user"
FOR EACH ROW
WHEN (NEW.deleted = true AND OLD.deleted = false)
EXECUTE FUNCTION fn_set_deleted_at();

---- create above / drop below ----

-- Write your migrate down statements here. If this migration is irreversible
-- Then delete the separator line above.

DROP TRIGGER IF EXISTS trg_user_check_age ON "user";
DROP TRIGGER IF EXISTS trg_user_updated_at ON "user";
DROP TRIGGER IF EXISTS trg_user_soft_delete ON "user";

DROP TABLE IF EXISTS "user";
