-- Write your migrate up statements here
CREATE TABLE IF NOT EXISTS "password" (
    password_id     integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         integer     NOT NULL UNIQUE REFERENCES "user"(user_id) ON DELETE CASCADE,
    password_hash   text        NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE  "password"                IS 'Записи о всех хэшах паролей пользователей';
COMMENT ON COLUMN "password".password_hash  IS 'Хэш пароля';

CREATE OR REPLACE TRIGGER trg_password_updated_at
BEFORE UPDATE ON "password"
FOR EACH ROW
WHEN (OLD.* IS DISTINCT FROM NEW.*)
EXECUTE FUNCTION fn_set_updated_at();

---- create above / drop below ----

-- Write your migrate down statements here. If this migration is irreversible
-- Then delete the separator line above.

DROP TRIGGER IF EXISTS trg_password_updated_at ON "password";

DROP TABLE IF EXISTS "password";
