-- Write your migrate up statements here
CREATE TABLE IF NOT EXISTS pin (
    pin_id          integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creator_id      integer     NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
    image_url       text        NOT NULL UNIQUE,
    name            text        NOT NULL,
    description     text,
    deleted         boolean     NOT NULL DEFAULT false,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    deleted_at      timestamptz
);

COMMENT ON TABLE  pin             IS 'Пины — публикации изображений';
COMMENT ON COLUMN pin.image_url   IS 'Ссылка на изображение в MinIO';
COMMENT ON COLUMN pin.deleted     IS 'так реализован soft delete: если delete = true — учётная запись удалёна';
COMMENT ON COLUMN pin.deleted_at  IS 'Момент soft delete; Если NULL, то запись активна';

CREATE OR REPLACE TRIGGER trg_pin_updated_at
BEFORE UPDATE ON pin
FOR EACH ROW
WHEN (OLD.* IS DISTINCT FROM NEW.*)
EXECUTE FUNCTION fn_set_updated_at();

CREATE OR REPLACE TRIGGER trg_pin_soft_delete
BEFORE UPDATE ON pin
FOR EACH ROW
WHEN (NEW.deleted = true AND OLD.deleted = false)
EXECUTE FUNCTION fn_set_deleted_at();

---- create above / drop below ----

-- Write your migrate down statements here. If this migration is irreversible
-- Then delete the separator line above.

DROP TRIGGER IF EXISTS trg_pin_updated_at ON "pin";
DROP TRIGGER IF EXISTS trg_pin_soft_delete ON "pin";

DROP TABLE IF EXISTS "pin";
