FROM golang:1.27-alpine AS build

RUN go install github.com/jackc/tern/v2@v2.4.2

FROM alpine:3.22

WORKDIR /app

COPY --from=build /go/bin/tern /usr/local/bin/tern

COPY db/tern.conf ./tern.conf
COPY db/migrations ./migrations

ENTRYPOINT ["tern", "migrate", "--config", "tern.conf", "--migrations", "migrations"]
