CREATE TABLE IF NOT EXISTS "user" (
    user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    user_tag text NOT NULL UNIQUE,
    birth_date date NOT NULL,
    description text,
    avatar_url text UNIQUE,
    deleted boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);

COMMENT ON TABLE "user" IS 'Учётные записи пользователей';
COMMENT ON COLUMN "user".user_tag IS 'Уникальный тег для поиска';
COMMENT ON COLUMN "user".avatar_url IS 'Ссылка на аватар';
COMMENT ON COLUMN "user".deleted IS 'Так реализован soft delete: если delete = true — запись удалёна';
COMMENT ON COLUMN "user".deleted_at IS 'Момент soft delete; Если NULL, то запись активна';

CREATE TABLE IF NOT EXISTS user_auth (
    user_id integer PRIMARY KEY REFERENCES "user"(user_id) ON DELETE CASCADE,
    password_hash text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pin (
    pin_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creator_id integer NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
    image_url text NOT NULL UNIQUE,
    name text NOT NULL,
    description text,
    deleted boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);

COMMENT ON TABLE pin IS 'Пины — публикации изображений';
COMMENT ON COLUMN pin.image_url IS 'Имя файла изображения пина';
COMMENT ON COLUMN pin.deleted IS 'Так реализован soft delete: если deleted = true — запись удалена';
COMMENT ON COLUMN pin.deleted_at IS 'Момент soft delete; Если NULL, то запись активна';

CREATE INDEX IF NOT EXISTS idx_pin_created_at_active
    ON pin (created_at DESC, pin_id DESC)
    WHERE deleted = false;

CREATE INDEX IF NOT EXISTS idx_pin_creator_id_active
    ON pin (creator_id)
    WHERE deleted = false;
