CREATE TABLE "user" (
    user_id         integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            text        NOT NULL,
    user_tag        text        NOT NULL UNIQUE,
    age             integer     NOT NULL CHECK (age > 12),
    description     text,
    avatar_url      text        UNIQUE,
    deleted         boolean     NOT NULL DEFAULT false,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at      timestamptz
);

COMMENT ON TABLE  "user"             IS 'Учётные записи пользователей';
COMMENT ON COLUMN "user".user_tag    IS 'Уникальный тег для поиска';
COMMENT ON COLUMN "user".avatar_url  IS 'Ссылка на аватар в MinIO';
COMMENT ON COLUMN "user".deleted     IS 'Так реализован soft delete: если delete = true — учётная запись удалёна';
COMMENT ON COLUMN "user".deleted_at  IS 'Момент soft delete; Если NULL, то запись активна';
