CREATE TABLE desk (
    desk_id         integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creator_id      integer     NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
    name            text        NOT NULL DEFAULT 'Untitled desk',
    description     text,
    avatar_img_url  text,
    entry_status    smallint    NOT NULL DEFAULT 0 CHECK (entry_status IN (0, 1, 2)),
    deleted         boolean     NOT NULL DEFAULT false,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at      timestamptz
);

COMMENT ON TABLE  desk                IS 'Доски — коллекции пинов пользователя';
COMMENT ON COLUMN desk.name           IS 'Имя доски';
COMMENT ON COLUMN desk.avatar_img_url IS 'Ссылка на обложку в MinIO';
COMMENT ON COLUMN desk.entry_status   IS '0 — открытая, 1 — только для подписчиков, 2 — только для автора';
COMMENT ON COLUMN desk.deleted_at     IS 'Момент soft delete; Если NULL, то запись активна';