CREATE TABLE "password" (
    password_id     integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         integer     NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
    password_hash   text        NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
);

COMMENT ON TABLE  "password"                IS 'Записи о всех хэшах паролей пользователей';
COMMENT ON COLUMN "password".password_hash  IS 'Хэш пароля';
