CREATE TABLE pin (
    pin_id          integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creator_id      integer     NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
    image_url       text        NOT NULL UNIQUE,
    name            text        NOT NULL,
    description     text,
    deleted         boolean     NOT NULL DEFAULT false,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    deleted_at      timestamptz
);

COMMENT ON TABLE  pin             IS 'Пины — публикации изображений';
COMMENT ON COLUMN pin.image_url   IS 'Ссылка на изображение в MinIO';
COMMENT ON COLUMN pin.deleted     IS 'так реализован soft delete: если delete = true — учётная запись удалёна';
COMMENT ON COLUMN pin.deleted_at  IS 'Момент soft delete; Если NULL, то запись активна';
