CREATE TABLE commentary (
    comment_id      integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id       integer     NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
    post_id         integer     NOT NULL REFERENCES pin(pin_id) ON DELETE CASCADE,
    body            text        NOT NULL,
    deleted         boolean     NOT NULL DEFAULT false,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at      timestamptz
);

COMMENT ON TABLE  commentary            IS 'Комментарии пользователей к пинам';
COMMENT ON COLUMN commentary.deleted    IS 'так реализован soft delete: если delete = true — учётная запись удалёна';
COMMENT ON COLUMN commentary.deleted_at IS 'Момент soft delete; Если NULL, то запись активна';