CREATE TABLE pin_like (
    pin_like_id integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    liker_id    integer     NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
    post_id     integer     NOT NULL REFERENCES pin(pin_id) ON DELETE CASCADE,
    created_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pin_like_unique_liker_post UNIQUE (liker_id, post_id)
);

COMMENT ON TABLE  pin_like IS 'Лайки пинов; один пользователь — один лайк на пин';
COMMENT ON CONSTRAINT pin_like_unique_liker_post ON pin_like IS 'Обеспечивает то, что от одного пользователя возможен только один лайк';