CREATE TABLE comment_like (
    comm_like_id integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    commenter_id integer     NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
    comm_id      integer     NOT NULL REFERENCES commentary(comment_id) ON DELETE CASCADE,
    created_at   timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT comment_like_unique_commenter_comm UNIQUE (commenter_id, comm_id)
);

COMMENT ON TABLE  comment_like IS 'Лайки комментариев';
COMMENT ON CONSTRAINT comment_like_unique_commenter_comm ON comment_like IS 'Обеспечивает то, что один пользователь может поставить один лайк';
