CREATE TABLE subscription (
    subscription_id integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscribee_id   integer     NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
    subscriber_id   integer     NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
    created_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT subscription_unique_pair UNIQUE (subscribee_id, subscriber_id),
    CONSTRAINT subscription_no_self     CHECK (subscribee_id <> subscriber_id)
);

COMMENT ON TABLE  subscription IS 'Подписки: subscriber следит за subscribee';
COMMENT ON CONSTRAINT subscription_no_self ON subscription IS 'Запрещает самоподписку';
COMMENT ON subscription_unique_pair IS 'Обеспечивает, что один пользователь может подписаться на другого только один раз'
