CREATE TABLE pin_desk_relation (
    desk_relation_id integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    desk_id          integer     NOT NULL REFERENCES desk(desk_id) ON DELETE CASCADE,
    pin_id           integer     NOT NULL REFERENCES pin(pin_id) ON DELETE CASCADE,
    created_at       timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pin_desk_relation_unique UNIQUE (desk_id, pin_id)
);

COMMENT ON TABLE  pin_desk_relation IS 'Связь пинов и досок';
COMMENT ON CONSTRAINT pin_desk_relation_unique ON pin_desk_relation IS 'Обеспечивает то, что один пин может быть на одной доске только один раз';
