CREATE TABLE tag (
    tag_id     integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       text        NOT NULL UNIQUE,
    created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE tag IS 'Теги для поиска пинов';