CREATE TABLE chat (
    chat_id    integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_a_id  integer     NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
    user_b_id  integer     NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
    name       text        NOT NULL,
    deleted    boolean     NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    CONSTRAINT chat_unique_pair      UNIQUE (user_a_id, user_b_id),
    CONSTRAINT chat_no_self          CHECK (user_a_id <> user_b_id)
);

COMMENT ON TABLE  chat                  IS 'Личные чаты между двумя пользователями';
COMMENT ON COLUMN chat.user_a_id        IS 'Участник диалога а';
COMMENT ON COLUMN chat.user_b_id        IS 'Участник диалога б';
COMMENT ON CONSTRAINT chat_no_self ON chat IS 'Запрещает чат с самим собой';
