CREATE TABLE pin_tag_relation (
    tag_relation_id integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_id          integer     NOT NULL REFERENCES tag(tag_id) ON DELETE CASCADE,
    pin_id          integer     NOT NULL REFERENCES pin(pin_id) ON DELETE CASCADE,
    created_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pin_tag_relation_unique UNIQUE (tag_id, pin_id)
);

COMMENT ON TABLE  pin_tag_relation IS 'Связь пинов и тегов';
COMMENT ON CONSTRAINT pin_tag_relation_unique ON pin_tag_relation IS 'Обеспечивает, что один тег может быть у одного пина единожды';
