CREATE TABLE chat_message (
    message_id integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id    integer     NOT NULL REFERENCES chat(chat_id) ON DELETE CASCADE,
    author_id  integer     NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
    body       text        NOT NULL,
    related_to integer REFERENCES chat_message(message_id) ON DELETE SET NULL,
    deleted    boolean     NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    CONSTRAINT chat_message_no_self_reply CHECK (related_to IS NULL OR related_to <> message_id)
);

COMMENT ON TABLE  chat_message            IS 'Сообщения в чате';
COMMENT ON COLUMN chat_message.related_to IS 'Показывает, на какое сообщение отвечает данное';
COMMENT ON COLUMN chat_message.deleted_at IS 'Момент soft delete; Если NULL, то запись активна';
