CREATE TABLE user_session (
    session_id    integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       integer     NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
    session_start timestamptz NOT NULL,
    session_end   timestamptz NOT NULL,
    CONSTRAINT user_session_valid_range CHECK (session_end > session_start)
);

COMMENT ON TABLE  user_session            IS 'История завершённых сессий';
COMMENT ON COLUMN user_session.session_start IS 'Начало сессии';
COMMENT ON COLUMN user_session.session_end   IS 'Конец сессии';
